export const REQUEST_INCREMENT = 'REQUEST_INCREMENT';
export const INCREMENT = 'INCREMENT';
export const REQUEST_GET_PROJECTS = 'REQUEST_GET_PROJECTS';
export const GET_PROJECTS = 'GET_PROJECTS';
